# 境内入口配置，用户自行区分
# Session管理（可选）
idle_session_check_interval: "30s"
idle_session_timeout: "5s"
min_idle_session: 2

tunnels:         # 支持多组转发
  - listen: "[::]:44713"        # 监听地址，支持TCP and UDP 连接
    remote: "your-vps.com:44713"    # 境外出口服务器地址
    sni: "bing.com"     # TLS伪装域名
    insecure: true     # Let's Encrypt请注释本行
    password: "lMgab3FiW5"     # 与出口保持一致

  - listen: "[::]:44716"        # 监听地址，支持TCP and UDP 连接
    remote: "your-vps.com:44716"    # 境外出口服务器地址
    sni: "bing.com"     # TLS伪装域名
    insecure: true     # Let's Encrypt 请注释本行
    password: "lMgab3FiW5"     # 与出口保持一致


# 境外出口配置，用户自行区分
# 自定义 PaddingScheme（可选，留空使用默认值）
padding_scheme: |
  stop=8
  0=30-30
  1=100-400
  2=400-500,c,500-1000,c,500-1000,c,500-1000,c,500-1000
  3=9-9,500-1000
  4=500-1000
  5=500-1000
  6=500-1000
  7=500-1000

tunnels:         # 支持多组转发
  - listen: "[::]:44713"         # 监听地址，接受境内入口连接,支持TCP and UDP 连接
    remote: "127.0.0.1:25256"  # 目标服务器
    sni: "bing.com"     # TLS伪装域名
    password: "lMgab3FiW5"     # 与入口保持一致
    cert: "/var/anygo/server.crt"     # 证书路径（自签 or Let's Encrypt）
    key:  "/var/anygo/server.key"     # 私钥路径（自签 or Let's Encrypt）

  - listen: "[::]:44716"         # 监听地址，接受境内入口连接,支持TCP and UDP 连接
    remote: "127.0.0.1:25256"  # 目标服务器
    sni: "bing.com"     # TLS伪装域名
    password: "lMgab3FiW5"     # 与入口保持一致
    cert: "/var/anygo/server.crt"     # 证书路径（自签or Let's Encrypt）
    key:  "/var/anygo/server.key"     # 私钥路径（自签or Let's Encrypt）
