# 入口配置示例，自行区分
listen: "0.0.0.0:1080"        # 监听隧道入口（客户端连这里）
remote: "your-vps.com:443"   # 境外出口服务器地址
sni: "www.cloudflare.com"    # TLS伪装域名（需是真实存在的域名）
password: "your-password"    # 认证密钥（与出口保持一致）
padding:
  templates: [64, 128, 256, 512, 1024, 1440, 2048]


# 出口配置示例，自行区分
listen: "0.0.0.0:443"         # 监听隧道出口（接受境内节点连接）
remote: "149.154.167.51:443" # 目标服务器（如Telegram服务器）
cert: "/etc/letsencrypt/live/example.com/fullchain.pem"
key:  "/etc/letsencrypt/live/example.com/privkey.pem"
password: "your-password"    # 认证密钥（与入口保持一致）
padding:
  templates: [64, 128, 256, 512, 1024, 1440, 2048]
